### ISSUE TITLE
Nette 2.3 security.userStorage

### ISSUE THREAD

**Issue by Olicek** [Majkl578/nette-identity-doctrine#4]
Hi,
I have just found problem in Nette 2.3. There is checker instance of object in DIC now. It try to create Nette\Http\UserStorage, probably because wrong name of service (`nette.userStorage` instead of `security.userStorage`). I tried change
```
$builder->getDefinition('nette.userStorage')
			->setClass('Majkl578\NetteAddons\Doctrine2Identity\Http\UserStorage');
```
instead of 
```
$builder->getDefinition('security.userStorage')
			->setClass('Majkl578\NetteAddons\Doctrine2Identity\Http\UserStorage');
```
But it had no effect. What is working for me is change it in neon.config
```
service:
    security.userStorage: Majkl578\NetteAddons\Doctrine2Identity\Http\UserStorage
```

**Comment by Lexinek** [comment]
I have same issue, anyways the fix @Olicek mentioned is working for me as well.

**Comment by haltuf** [comment]
I had the same problem, thanks for the fast workaround, @Olicek !
